/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

/**
 *
 * @author Kiko e Dan
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCafeLeite = new javax.swing.JButton();
        btnExpresso = new javax.swing.JButton();
        btnCappuccino = new javax.swing.JButton();
        btnMacchiato = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cafeteria");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagens/cafe com leite.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 120, 100, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagens/Expresso.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 262, 100, 93);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagens/capuchino.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(322, 120, 100, 100);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(316, 238, 0, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagens/Macchiato.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(343, 248, 67, 100);

        btnCafeLeite.setText("Café com Leite");
        getContentPane().add(btnCafeLeite);
        btnCafeLeite.setBounds(154, 172, 103, 23);

        btnExpresso.setText("Expresso");
        getContentPane().add(btnExpresso);
        btnExpresso.setBounds(154, 298, 77, 23);

        btnCappuccino.setText("Cappuccino");
        getContentPane().add(btnCappuccino);
        btnCappuccino.setBounds(440, 170, 87, 23);

        btnMacchiato.setText("Macchiato");
        getContentPane().add(btnMacchiato);
        btnMacchiato.setBounds(440, 296, 81, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bem vindo a Cafeteria!");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 20, 150, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Escolha seu café:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 60, 120, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCafeLeite;
    private javax.swing.JButton btnCappuccino;
    private javax.swing.JButton btnExpresso;
    private javax.swing.JButton btnMacchiato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
